---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- Infrastructure:
    - Portainer:
        icon: portainer.png
        href: https://portainer.local.pfeferki.com
        description: Portainer@Centaurus server
        widget:
            type: portainer
            url: https://10.0.1.135:9443
            env: 2
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Proxmox:
        icon: proxmox.png
        href: https://pve1.local.pfeferki.com
        description: PVE Proxmox Server
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_PVE1_URL}}
            username: {{HOMEPAGE_VAR_PVE1_USER}}
            password: {{HOMEPAGE_VAR_PVE1_PASSWD}}
    - Adguard Home:
        icon: adguard-home.svg
        href: https://adguard.local.pfeferki.com
        description: Add blocking
        widget:
            type: adguard
            url: {{HOMEPAGE_VAR_ADGUARD_URL}}
            username: {{HOMEPAGE_VAR_ADGUARD_USER}}
            password: {{HOMEPAGE_VAR_ADGUARD_PASSWD}}

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://10.0.1.135:3010
        description: Uptime kuma on Polaris
        widget:
            type: uptimekuma
            url: http://10.0.1.135:3010
            slug: services
    - PBS:
        icon: proxmox.png
        href: https://pbs.local.pfeferki.com
        description: Proxmox Backup Server
        widget:
            type: proxmoxbackupserver
            fields: ["datastore_usage", "failed_tasks_24h"]
            url: {{HOMEPAGE_VAR_PBS_URL}}
            username: {{HOMEPAGE_VAR_PBS_USER}}
            password: {{HOMEPAGE_VAR_PBS_PASSWD}}
    - FreshRss:
        icon: freshrss.png
        href: https://news.pfeferki.com
        description: FreshRSS News Server
        widget:
            type: freshrss
            url: http://10.0.1.135:8051
            username: {{HOMEPAGE_VAR_FRESHRSS_USER}}
            password: {{HOMEPAGE_VAR_FRESHRSS_PASSWD}}

- Network:
    - Traefik:
        icon: traefik.png
        href: http://10.0.1.135:8888
        description: Traefik Polaris Server
        widget:
            type: traefik
            url: http://10.0.1.135:8888
            fields: ["routers", "services", "middleware"]
    - Unifi:
        icon: unifi.png
        href: https://192.168.1.1
        description: UniFi Express Local 
        widget:
            type: unifi
            url: {{HOMEPAGE_VAR_UNIFI_URL}} 
            username: {{HOMEPAGE_VAR_UNIFI_USER}}
            password: {{HOMEPAGE_VAR_UNIFI_PASSWD}}

- Applications:
    - Firefly:
        icon: firefly.png
        href: https://firefly.pfeferki.com
        description: Financial system
    - Firefly Importer:
        href: https://importer.local.pfeferki.com
        description: Firefly III Importer
- Home:
    - Home Assistant:
        icon: home-assistant.png
        href: https://home.pfeferki.com
        description: Homme Piaseczno
    - Home Assistant Niestachów:
        icon: home-assistant.png
        href: https://home.pfefer.xyz
        description: Homme Niestachow
    - Shinobi:
        icon: shinobi.png
        href: https://shinobi.local.pfefer.xyz
        description: Shinobi CCTV Niestachów
- Tools:
    - Grafana:
        icon: grafana.png
        href: https://grafana.pfeferki.com
        description: Grafana polaris
    - InfluxDB:
        icon: influxdb.png
        href: https://influxdb.pfeferki.com
        description: Influxdb polaris
    - MinIO:
        icon: minio.png
        href: https://minio-console.local.pfeferki.com
        description: Minio telesfor
    - NUT:
        icon: mdi:battery-high
        href: https://ups.local.pfefer.xyz/cgi-bin/nut/upsstats.cgi
        description: Basement UPS    
- Entertainment:
    - Plex:
        icon: plex.png
        href: https://plex.pfeferki.com
        description: Plex media server 
